window.esdocSearchIndex = [
  [
    "lazer-game-core/src/bullet/bullet.js~bullet",
    "class/src/bullet/Bullet.js~Bullet.html",
    "<span>Bullet</span> <span class=\"search-result-import-path\">lazer-game-core/src/bullet/Bullet.js</span>",
    "class"
  ],
  [
    "lazer-game-core/src/bullet/bulletmanager.js~bulletmanager",
    "class/src/bullet/BulletManager.js~BulletManager.html",
    "<span>BulletManager</span> <span class=\"search-result-import-path\">lazer-game-core/src/bullet/BulletManager.js</span>",
    "class"
  ],
  [
    "lazer-game-core/src/const.js~collision_groups",
    "variable/index.html#static-variable-COLLISION_GROUPS",
    "<span>COLLISION_GROUPS</span> <span class=\"search-result-import-path\">lazer-game-core/src/const.js</span>",
    "variable"
  ],
  [
    "lazer-game-core/src/bullet/types/defaultbullet.js~defaultbullet",
    "class/src/bullet/types/DefaultBullet.js~DefaultBullet.html",
    "<span>DefaultBullet</span> <span class=\"search-result-import-path\">lazer-game-core/src/bullet/types/DefaultBullet.js</span>",
    "class"
  ],
  [
    "lazer-game-core/src/game/game.js~game",
    "class/src/game/Game.js~Game.html",
    "<span>Game</span> <span class=\"search-result-import-path\">lazer-game-core/src/game/Game.js</span>",
    "class"
  ],
  [
    "lazer-game-core/src/player/player.js~player",
    "class/src/player/Player.js~Player.html",
    "<span>Player</span> <span class=\"search-result-import-path\">lazer-game-core/src/player/Player.js</span>",
    "class"
  ],
  [
    "lazer-game-core/src/player/playermanager.js~playermanager",
    "class/src/player/PlayerManager.js~PlayerManager.html",
    "<span>PlayerManager</span> <span class=\"search-result-import-path\">lazer-game-core/src/player/PlayerManager.js</span>",
    "class"
  ],
  [
    "lazer-game-core/src/tilemap/tilemap.js~tilemap",
    "class/src/tilemap/Tilemap.js~Tilemap.html",
    "<span>Tilemap</span> <span class=\"search-result-import-path\">lazer-game-core/src/tilemap/Tilemap.js</span>",
    "class"
  ],
  [
    "lazer-game-core/src/utils.js~buildcollisions",
    "function/index.html#static-function-buildCollisions",
    "<span>buildCollisions</span> <span class=\"search-result-import-path\">lazer-game-core/src/utils.js</span>",
    "function"
  ],
  [
    "lazer-game-core/src/utils.js~clipdecimals",
    "function/index.html#static-function-clipDecimals",
    "<span>clipDecimals</span> <span class=\"search-result-import-path\">lazer-game-core/src/utils.js</span>",
    "function"
  ],
  [
    "lazer-game-core/src/utils.js~lerp",
    "function/index.html#static-function-lerp",
    "<span>lerp</span> <span class=\"search-result-import-path\">lazer-game-core/src/utils.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/bullet/bullet.js",
    "file/src/bullet/Bullet.js.html",
    "src/bullet/Bullet.js",
    "file"
  ],
  [
    "src/bullet/bullet.js~bullet#constructor",
    "class/src/bullet/Bullet.js~Bullet.html#instance-constructor-constructor",
    "src/bullet/Bullet.js~Bullet#constructor",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#data",
    "class/src/bullet/Bullet.js~Bullet.html#instance-member-data",
    "src/bullet/Bullet.js~Bullet#data",
    "member"
  ],
  [
    "src/bullet/bullet.js~bullet#destroy",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-destroy",
    "src/bullet/Bullet.js~Bullet#destroy",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#die",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-die",
    "src/bullet/Bullet.js~Bullet#die",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#emit",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-emit",
    "src/bullet/Bullet.js~Bullet#emit",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#fromjson",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-fromJSON",
    "src/bullet/Bullet.js~Bullet#fromJSON",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#game",
    "class/src/bullet/Bullet.js~Bullet.html#instance-get-game",
    "src/bullet/Bullet.js~Bullet#game",
    "member"
  ],
  [
    "src/bullet/bullet.js~bullet#getprop",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-getProp",
    "src/bullet/Bullet.js~Bullet#getProp",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#id",
    "class/src/bullet/Bullet.js~Bullet.html#instance-member-id",
    "src/bullet/Bullet.js~Bullet#id",
    "member"
  ],
  [
    "src/bullet/bullet.js~bullet#info",
    "class/src/bullet/Bullet.js~Bullet.html#instance-member-info",
    "src/bullet/Bullet.js~Bullet#info",
    "member"
  ],
  [
    "src/bullet/bullet.js~bullet#init",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-init",
    "src/bullet/Bullet.js~Bullet#init",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#manager",
    "class/src/bullet/Bullet.js~Bullet.html#instance-member-manager",
    "src/bullet/Bullet.js~Bullet#manager",
    "member"
  ],
  [
    "src/bullet/bullet.js~bullet#player",
    "class/src/bullet/Bullet.js~Bullet.html#instance-get-player",
    "src/bullet/Bullet.js~Bullet#player",
    "member"
  ],
  [
    "src/bullet/bullet.js~bullet#props",
    "class/src/bullet/Bullet.js~Bullet.html#instance-member-props",
    "src/bullet/Bullet.js~Bullet#props",
    "member"
  ],
  [
    "src/bullet/bullet.js~bullet#setprop",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-setProp",
    "src/bullet/Bullet.js~Bullet#setProp",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#tojson",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-toJSON",
    "src/bullet/Bullet.js~Bullet#toJSON",
    "method"
  ],
  [
    "src/bullet/bullet.js~bullet#type",
    "class/src/bullet/Bullet.js~Bullet.html#instance-get-type",
    "src/bullet/Bullet.js~Bullet#type",
    "member"
  ],
  [
    "src/bullet/bullet.js~bullet#update",
    "class/src/bullet/Bullet.js~Bullet.html#instance-method-update",
    "src/bullet/Bullet.js~Bullet#update",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js",
    "file/src/bullet/BulletManager.js.html",
    "src/bullet/BulletManager.js",
    "file"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#bullets",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-member-bullets",
    "src/bullet/BulletManager.js~BulletManager#bullets",
    "member"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#clearbullets",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-clearBullets",
    "src/bullet/BulletManager.js~BulletManager#clearBullets",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#constructor",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-constructor-constructor",
    "src/bullet/BulletManager.js~BulletManager#constructor",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#createbullet",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-createBullet",
    "src/bullet/BulletManager.js~BulletManager#createBullet",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#createfromjson",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-createFromJSON",
    "src/bullet/BulletManager.js~BulletManager#createFromJSON",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#fromjson",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-fromJSON",
    "src/bullet/BulletManager.js~BulletManager#fromJSON",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#game",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-member-game",
    "src/bullet/BulletManager.js~BulletManager#game",
    "member"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#getbullet",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-getBullet",
    "src/bullet/BulletManager.js~BulletManager#getBullet",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#getbullettype",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-getBulletType",
    "src/bullet/BulletManager.js~BulletManager#getBulletType",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#removebullet",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-removeBullet",
    "src/bullet/BulletManager.js~BulletManager#removeBullet",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#tojson",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-toJSON",
    "src/bullet/BulletManager.js~BulletManager#toJSON",
    "method"
  ],
  [
    "src/bullet/bulletmanager.js~bulletmanager#update",
    "class/src/bullet/BulletManager.js~BulletManager.html#instance-method-update",
    "src/bullet/BulletManager.js~BulletManager#update",
    "method"
  ],
  [
    "src/bullet/types/defaultbullet.js",
    "file/src/bullet/types/DefaultBullet.js.html",
    "src/bullet/types/DefaultBullet.js",
    "file"
  ],
  [
    "src/bullet/types/defaultbullet.js~defaultbullet#init",
    "class/src/bullet/types/DefaultBullet.js~DefaultBullet.html#instance-method-init",
    "src/bullet/types/DefaultBullet.js~DefaultBullet#init",
    "method"
  ],
  [
    "src/bullet/types/defaultbullet.js~defaultbullet#update",
    "class/src/bullet/types/DefaultBullet.js~DefaultBullet.html#instance-method-update",
    "src/bullet/types/DefaultBullet.js~DefaultBullet#update",
    "method"
  ],
  [
    "src/bullet/types/defaultbullet.js~defaultbullet.calcpath",
    "class/src/bullet/types/DefaultBullet.js~DefaultBullet.html#static-method-calcPath",
    "src/bullet/types/DefaultBullet.js~DefaultBullet.calcPath",
    "method"
  ],
  [
    "src/bullet/types/defaultbullet.js~defaultbullet.directiononpath",
    "class/src/bullet/types/DefaultBullet.js~DefaultBullet.html#static-method-directionOnPath",
    "src/bullet/types/DefaultBullet.js~DefaultBullet.directionOnPath",
    "method"
  ],
  [
    "src/bullet/types/defaultbullet.js~defaultbullet.pointonpath",
    "class/src/bullet/types/DefaultBullet.js~DefaultBullet.html#static-method-pointOnPath",
    "src/bullet/types/DefaultBullet.js~DefaultBullet.pointOnPath",
    "method"
  ],
  [
    "src/const.js",
    "file/src/const.js.html",
    "src/const.js",
    "file"
  ],
  [
    "src/game/game.js",
    "file/src/game/Game.js.html",
    "src/game/Game.js",
    "file"
  ],
  [
    "src/game/game.js~game#bullets",
    "class/src/game/Game.js~Game.html#instance-member-bullets",
    "src/game/Game.js~Game#bullets",
    "member"
  ],
  [
    "src/game/game.js~game#config",
    "class/src/game/Game.js~Game.html#instance-member-config",
    "src/game/Game.js~Game#config",
    "member"
  ],
  [
    "src/game/game.js~game#constructor",
    "class/src/game/Game.js~Game.html#instance-constructor-constructor",
    "src/game/Game.js~Game#constructor",
    "method"
  ],
  [
    "src/game/game.js~game#createplayer",
    "class/src/game/Game.js~Game.html#instance-method-createPlayer",
    "src/game/Game.js~Game#createPlayer",
    "method"
  ],
  [
    "src/game/game.js~game#fromjson",
    "class/src/game/Game.js~Game.html#instance-method-fromJSON",
    "src/game/Game.js~Game#fromJSON",
    "method"
  ],
  [
    "src/game/game.js~game#getdelta",
    "class/src/game/Game.js~Game.html#instance-method-getDelta",
    "src/game/Game.js~Game#getDelta",
    "method"
  ],
  [
    "src/game/game.js~game#getinfo",
    "class/src/game/Game.js~Game.html#instance-method-getInfo",
    "src/game/Game.js~Game#getInfo",
    "method"
  ],
  [
    "src/game/game.js~game#getplayer",
    "class/src/game/Game.js~Game.html#instance-method-getPlayer",
    "src/game/Game.js~Game#getPlayer",
    "method"
  ],
  [
    "src/game/game.js~game#id",
    "class/src/game/Game.js~Game.html#instance-member-id",
    "src/game/Game.js~Game#id",
    "member"
  ],
  [
    "src/game/game.js~game#info",
    "class/src/game/Game.js~Game.html#instance-member-info",
    "src/game/Game.js~Game#info",
    "member"
  ],
  [
    "src/game/game.js~game#isclient",
    "class/src/game/Game.js~Game.html#instance-get-isClient",
    "src/game/Game.js~Game#isClient",
    "member"
  ],
  [
    "src/game/game.js~game#ismaster",
    "class/src/game/Game.js~Game.html#instance-member-isMaster",
    "src/game/Game.js~Game#isMaster",
    "member"
  ],
  [
    "src/game/game.js~game#lastdelta",
    "class/src/game/Game.js~Game.html#instance-member-lastDelta",
    "src/game/Game.js~Game#lastDelta",
    "member"
  ],
  [
    "src/game/game.js~game#map",
    "class/src/game/Game.js~Game.html#instance-member-map",
    "src/game/Game.js~Game#map",
    "member"
  ],
  [
    "src/game/game.js~game#players",
    "class/src/game/Game.js~Game.html#instance-member-players",
    "src/game/Game.js~Game#players",
    "member"
  ],
  [
    "src/game/game.js~game#removeplayer",
    "class/src/game/Game.js~Game.html#instance-method-removePlayer",
    "src/game/Game.js~Game#removePlayer",
    "method"
  ],
  [
    "src/game/game.js~game#setinfo",
    "class/src/game/Game.js~Game.html#instance-method-setInfo",
    "src/game/Game.js~Game#setInfo",
    "method"
  ],
  [
    "src/game/game.js~game#spawnplayer",
    "class/src/game/Game.js~Game.html#instance-method-spawnPlayer",
    "src/game/Game.js~Game#spawnPlayer",
    "method"
  ],
  [
    "src/game/game.js~game#tojson",
    "class/src/game/Game.js~Game.html#instance-method-toJSON",
    "src/game/Game.js~Game#toJSON",
    "method"
  ],
  [
    "src/game/game.js~game#update",
    "class/src/game/Game.js~Game.html#instance-method-update",
    "src/game/Game.js~Game#update",
    "method"
  ],
  [
    "src/game/game.js~game#world",
    "class/src/game/Game.js~Game.html#instance-member-world",
    "src/game/Game.js~Game#world",
    "member"
  ],
  [
    "src/game/gameconfig.js",
    "file/src/game/gameConfig.js.html",
    "src/game/gameConfig.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/player/player.js",
    "file/src/player/Player.js.html",
    "src/player/Player.js",
    "file"
  ],
  [
    "src/player/player.js~player#_updateposition",
    "class/src/player/Player.js~Player.html#instance-method-_updatePosition",
    "src/player/Player.js~Player#_updatePosition",
    "method"
  ],
  [
    "src/player/player.js~player#body",
    "class/src/player/Player.js~Player.html#instance-member-body",
    "src/player/Player.js~Player#body",
    "member"
  ],
  [
    "src/player/player.js~player#constructor",
    "class/src/player/Player.js~Player.html#instance-constructor-constructor",
    "src/player/Player.js~Player#constructor",
    "method"
  ],
  [
    "src/player/player.js~player#controls",
    "class/src/player/Player.js~Player.html#instance-member-controls",
    "src/player/Player.js~Player#controls",
    "member"
  ],
  [
    "src/player/player.js~player#cooldown",
    "class/src/player/Player.js~Player.html#instance-member-cooldown",
    "src/player/Player.js~Player#cooldown",
    "member"
  ],
  [
    "src/player/player.js~player#emit",
    "class/src/player/Player.js~Player.html#instance-method-emit",
    "src/player/Player.js~Player#emit",
    "method"
  ],
  [
    "src/player/player.js~player#fromjson",
    "class/src/player/Player.js~Player.html#instance-method-fromJSON",
    "src/player/Player.js~Player#fromJSON",
    "method"
  ],
  [
    "src/player/player.js~player#game",
    "class/src/player/Player.js~Player.html#instance-get-game",
    "src/player/Player.js~Player#game",
    "member"
  ],
  [
    "src/player/player.js~player#getcontrol",
    "class/src/player/Player.js~Player.html#instance-method-getControl",
    "src/player/Player.js~Player#getControl",
    "method"
  ],
  [
    "src/player/player.js~player#getinfo",
    "class/src/player/Player.js~Player.html#instance-method-getInfo",
    "src/player/Player.js~Player#getInfo",
    "method"
  ],
  [
    "src/player/player.js~player#getprop",
    "class/src/player/Player.js~Player.html#instance-method-getProp",
    "src/player/Player.js~Player#getProp",
    "method"
  ],
  [
    "src/player/player.js~player#id",
    "class/src/player/Player.js~Player.html#instance-member-id",
    "src/player/Player.js~Player#id",
    "member"
  ],
  [
    "src/player/player.js~player#info",
    "class/src/player/Player.js~Player.html#instance-member-info",
    "src/player/Player.js~Player#info",
    "member"
  ],
  [
    "src/player/player.js~player#manager",
    "class/src/player/Player.js~Player.html#instance-member-manager",
    "src/player/Player.js~Player#manager",
    "member"
  ],
  [
    "src/player/player.js~player#position",
    "class/src/player/Player.js~Player.html#instance-member-position",
    "src/player/Player.js~Player#position",
    "member"
  ],
  [
    "src/player/player.js~player#props",
    "class/src/player/Player.js~Player.html#instance-member-props",
    "src/player/Player.js~Player#props",
    "member"
  ],
  [
    "src/player/player.js~player#setcontrol",
    "class/src/player/Player.js~Player.html#instance-method-setControl",
    "src/player/Player.js~Player#setControl",
    "method"
  ],
  [
    "src/player/player.js~player#setinfo",
    "class/src/player/Player.js~Player.html#instance-method-setInfo",
    "src/player/Player.js~Player#setInfo",
    "method"
  ],
  [
    "src/player/player.js~player#setposition",
    "class/src/player/Player.js~Player.html#instance-method-setPosition",
    "src/player/Player.js~Player#setPosition",
    "method"
  ],
  [
    "src/player/player.js~player#setprop",
    "class/src/player/Player.js~Player.html#instance-method-setProp",
    "src/player/Player.js~Player#setProp",
    "method"
  ],
  [
    "src/player/player.js~player#tmp",
    "class/src/player/Player.js~Player.html#instance-member-tmp",
    "src/player/Player.js~Player#tmp",
    "member"
  ],
  [
    "src/player/player.js~player#tojson",
    "class/src/player/Player.js~Player.html#instance-method-toJSON",
    "src/player/Player.js~Player#toJSON",
    "method"
  ],
  [
    "src/player/player.js~player#update",
    "class/src/player/Player.js~Player.html#instance-method-update",
    "src/player/Player.js~Player#update",
    "method"
  ],
  [
    "src/player/playermanager.js",
    "file/src/player/PlayerManager.js.html",
    "src/player/PlayerManager.js",
    "file"
  ],
  [
    "src/player/playermanager.js~playermanager#clearplayers",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-method-clearPlayers",
    "src/player/PlayerManager.js~PlayerManager#clearPlayers",
    "method"
  ],
  [
    "src/player/playermanager.js~playermanager#constructor",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-constructor-constructor",
    "src/player/PlayerManager.js~PlayerManager#constructor",
    "method"
  ],
  [
    "src/player/playermanager.js~playermanager#createfromjson",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-method-createFromJSON",
    "src/player/PlayerManager.js~PlayerManager#createFromJSON",
    "method"
  ],
  [
    "src/player/playermanager.js~playermanager#createplayer",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-method-createPlayer",
    "src/player/PlayerManager.js~PlayerManager#createPlayer",
    "method"
  ],
  [
    "src/player/playermanager.js~playermanager#fromjson",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-method-fromJSON",
    "src/player/PlayerManager.js~PlayerManager#fromJSON",
    "method"
  ],
  [
    "src/player/playermanager.js~playermanager#game",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-member-game",
    "src/player/PlayerManager.js~PlayerManager#game",
    "member"
  ],
  [
    "src/player/playermanager.js~playermanager#getplayer",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-method-getPlayer",
    "src/player/PlayerManager.js~PlayerManager#getPlayer",
    "method"
  ],
  [
    "src/player/playermanager.js~playermanager#players",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-member-players",
    "src/player/PlayerManager.js~PlayerManager#players",
    "member"
  ],
  [
    "src/player/playermanager.js~playermanager#removeplayer",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-method-removePlayer",
    "src/player/PlayerManager.js~PlayerManager#removePlayer",
    "method"
  ],
  [
    "src/player/playermanager.js~playermanager#tojson",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-method-toJSON",
    "src/player/PlayerManager.js~PlayerManager#toJSON",
    "method"
  ],
  [
    "src/player/playermanager.js~playermanager#update",
    "class/src/player/PlayerManager.js~PlayerManager.html#instance-method-update",
    "src/player/PlayerManager.js~PlayerManager#update",
    "method"
  ],
  [
    "src/tilemap/tilemap.js",
    "file/src/tilemap/Tilemap.js.html",
    "src/tilemap/Tilemap.js",
    "file"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#bodies",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-member-bodies",
    "src/tilemap/Tilemap.js~Tilemap#bodies",
    "member"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#clearbodies",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-method-clearBodies",
    "src/tilemap/Tilemap.js~Tilemap#clearBodies",
    "method"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#constructor",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-constructor-constructor",
    "src/tilemap/Tilemap.js~Tilemap#constructor",
    "method"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#fromjson",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-method-fromJSON",
    "src/tilemap/Tilemap.js~Tilemap#fromJSON",
    "method"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#game",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-member-game",
    "src/tilemap/Tilemap.js~Tilemap#game",
    "member"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#getspawnpoint",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-method-getSpawnPoint",
    "src/tilemap/Tilemap.js~Tilemap#getSpawnPoint",
    "method"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#loadedjson",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-member-loadedJSON",
    "src/tilemap/Tilemap.js~Tilemap#loadedJSON",
    "member"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#size",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-member-size",
    "src/tilemap/Tilemap.js~Tilemap#size",
    "member"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#spawnareas",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-member-spawnAreas",
    "src/tilemap/Tilemap.js~Tilemap#spawnAreas",
    "member"
  ],
  [
    "src/tilemap/tilemap.js~tilemap#tojson",
    "class/src/tilemap/Tilemap.js~Tilemap.html#instance-method-toJSON",
    "src/tilemap/Tilemap.js~Tilemap#toJSON",
    "method"
  ],
  [
    "src/tilemap/tilemap.js~tilemap.buildcollisions",
    "class/src/tilemap/Tilemap.js~Tilemap.html#static-method-buildCollisions",
    "src/tilemap/Tilemap.js~Tilemap.buildCollisions",
    "method"
  ],
  [
    "src/tilemap/tilemap.js~tilemap.parsetiledjson",
    "class/src/tilemap/Tilemap.js~Tilemap.html#static-method-parseTiledJSON",
    "src/tilemap/Tilemap.js~Tilemap.parseTiledJSON",
    "method"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ]
]